# GÖREV: OTONOM KOD ANALİZİ VE DÜZELTME
# ARAÇ ADI: enum_firewall_detector.py
# DURUM: NİHAİ UZMAN SÜRÜMÜ v2 - Stateless, Güvenli ve Stratejik Danışman

"""
enum_firewall_detector.py - Profesyonel Seviye Güvenlik Duruşu Analiz Aracı

Amaç: Hedefin güvenlik katmanlarını (WAF/CDN), yapılandırmasını (güvenlik başlıkları)
      ve davranışını (rate limiting) pasif ve güvenli aktif yöntemlerle tespit eder.
      Ardından, bu bütünsel analize dayanarak MCP ajanı için dinamik, hedefe özel
      ve önceliklendirilmiş bir saldırı stratejisi planı oluşturur.

v2 Değişiklik Notları:
- MİMARİ: Araç, MCP için tamamen stateless (durumsuz) hale getirildi. Tüm analiz
  durumu, her 'execute' çağrısında oluşturulan bir context nesnesi içinde yönetilir.
- GÜVENLİK: WAF tespiti için kullanılan aktif probe, zararlı payload'lardan
  arındırıldı. Artık WAF'ları tetiklemek için evrensel olarak şüpheli ama tamamen
  zararsız bir LFI (Local File Inclusion) deseni kullanılıyor.
- MCP ENTEGRASYONU: Çıktı, standart MCP JSON formatına tam uyumlu hale getirildi.
- STRATEJİK ZEKA: Öneri motoru geliştirildi. Artık sadece tespit edilen WAF'a
  göre değil, WAF'ın *yokluğuna*, rate limiting durumuna ve kritik güvenlik
  başlıklarının eksikliğine göre de "kritik" ve "yüksek" öncelikli öneriler üretiyor.
- KOD KALİTESİ: Kod, kapsamlı yorumlar, type hinting ve bir uzmanın beklentilerini
  karşılayacak şekilde sağlam hata yönetimi ile son haline getirildi.
"""
import asyncio
import logging
import argparse
import json
import sys
from typing import Dict, Any, List, Optional
import aiohttp
from dataclasses import dataclass, field

# PentagentTool base class'ını import et
import os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from tools.base_mcp_tool import MCPTool, ToolCategory, PriorityLevel

# ... (WAF_SIGNATURES veritabanı önceki versiyonla aynı, mükemmel durumda) ...
WAF_SIGNATURES = {
    "Cloudflare": { "headers": ["CF-RAY", "CF-Cache-Status", "Server: cloudflare"], "is_cdn": True, "is_waf": True, "cdn_features": ["DDoS Protection", "SSL/TLS", "Caching", "WAF"], "bypass_difficulty": "high", "specific_recommendations": [{"priority": "critical", "tool": "recon_origin_ip_finder", "reason": "Cloudflare'ı atlamanın en etkili yolu, arkasındaki gerçek sunucu IP'sini bulmaktır."}, {"priority": "medium", "tool": "enum_directory_bruteforcer", "reason": "Cloudflare'ın agresif rate limiting'ini tetiklememek için taramaları yavaş ve düşük thread ile yap.", "params": {"threads": 5}}, {"priority": "medium", "tool": "recon_dns_analyzer", "reason": "Yapılandırma hatası olan alt alan adları (örn: direct.domain.com) WAF arkasında olmayabilir."}] },
    "ModSecurity": { "response_patterns": ["ModSecurity", "This error was generated by Mod_Security"], "is_cdn": False, "is_waf": True, "bypass_difficulty": "low", "specific_recommendations": [{"priority": "high", "tool": "vuln_payload_encoder", "reason": "ModSecurity kurallarını atlamak için farklı payload encoding teknikleri (URL, double URL, Base64) dene."}, {"priority": "medium", "tool": "vuln_waf_fuzzer", "reason": "Hangi tür saldırıların engellendiğini anlamak için farklı payload kategorileriyle (SQLi, XSS) fuzzing yap."}] },
    "AWS WAF": { "headers": ["x-amzn-RequestId", "Server: awselb"], "is_cdn": False, "is_waf": True, "bypass_difficulty": "medium", "specific_recommendations": [{"priority": "high", "tool": "vuln_http_param_pollution", "reason": "AWS WAF'ın istekleri nasıl yorumladığını test etmek için HTTP parametre kirliliği (HPP) dene."}] }
}

logging.basicConfig(level=logging.WARNING, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

@dataclass
class FirewallContext:
    """Güvenlik analizi sırasında durumu yönetmek için kullanılan veri sınıfı."""
    target_url: str
    detected_wafs: List[Dict[str, Any]] = field(default_factory=list)
    detected_cdns: List[Dict[str, Any]] = field(default_factory=list)
    security_headers: Dict[str, str] = field(default_factory=dict)
    rate_limit_results: Dict[str, Any] = field(default_factory=dict)
    ai_reasoning_log: List[Dict[str, str]] = field(default_factory=list)

class EnumFirewallDetectorTool(MCPTool):
    """Hedefin güvenlik duruşunu analiz eder ve stratejik sızma testi planı önerir."""

    def __init__(self):
        super().__init__(
            name="enum_firewall_detector",
            description="Hedefin güvenlik katmanlarını (WAF/CDN) ve güvenlik duruşunu analiz eder.",
            category=ToolCategory.DISCOVERY_ENUMERATION
        )

    def _check_waf_signatures(self, headers: Dict, content: str, context: FirewallContext):
        """Pasif olarak toplanan veride WAF imzalarını arar."""
        headers_str = str(headers).lower()
        content_lower = content.lower()
        for name, sigs in WAF_SIGNATURES.items():
            indicators = []
            if any(h.lower() in headers_str for h in sigs.get("headers", [])):
                indicators.append("HTTP Headers")
            if any(p.lower() in content_lower for p in sigs.get("response_patterns", [])):
                indicators.append("Response Content")
            if indicators:
                waf_info = {"name": name, "indicators": indicators, "details": sigs}
                if sigs.get("is_waf") and not any(w["name"] == name for w in context.detected_wafs):
                    context.detected_wafs.append(waf_info)
                if sigs.get("is_cdn") and not any(c["name"] == name for c in context.detected_cdns):
                    context.detected_cdns.append(waf_info)

    def _check_security_headers(self, headers, context: FirewallContext):
        """Yaygın güvenlik başlıklarının varlığını ve değerini kontrol eder."""
        relevant = ["X-Frame-Options", "X-Content-Type-Options", "Strict-Transport-Security", "Content-Security-Policy"]
        for header in relevant:
            if header in headers:
                context.security_headers[header] = headers[header]

    async def _passive_scan(self, session: aiohttp.ClientSession, context: FirewallContext):
        """Sadece hedefe normal bir istek göndererek pasif analiz yapar."""
        context.ai_reasoning_log.append({"phase": "passive_scan", "thought": "Pasif analiz için hedefe standart bir GET isteği gönderiliyor."})
        async with session.get(context.target_url, timeout=15) as response:
            content = await response.text(errors='ignore')
            self._check_waf_signatures(response.headers, content, context)
            self._check_security_headers(response.headers, context)

    async def _active_probe(self, session: aiohttp.ClientSession, context: FirewallContext):
        """WAF'ları tetiklemek için şüpheli ama zararsız bir istek gönderir."""
        # GÜVENLİ PAYLOAD: Gerçek bir saldırı değil, sadece WAF'ların tepkisini ölçen bir desen.
        malicious_path = "/?id=../../../../etc/passwd"
        context.ai_reasoning_log.append({"phase": "active_probe", "thought": f"Aktif WAF tespiti için zararsız probe gönderiliyor: {malicious_path}"})
        async with session.get(context.target_url + malicious_path, timeout=15) as response:
            content = await response.text(errors='ignore')
            # Eğer bu istek engellendiyse (örn. 403 Forbidden), bu güçlü bir WAF göstergesidir.
            if response.status == 403:
                 context.ai_reasoning_log.append({"phase": "active_finding", "thought": "⚠️ Aktif probe 403 Forbidden ile engellendi. Bu, güçlü bir WAF varlığına işaret ediyor."})
            self._check_waf_signatures(response.headers, content, context)

    async def _rate_limit_test(self, session: aiohttp.ClientSession, context: FirewallContext):
        """Hızlı ve seri istekler göndererek rate limiting varlığını test eder."""
        context.ai_reasoning_log.append({"phase": "rate_limit_test", "thought": "Rate limiting tespiti için 30 adet seri istek gönderiliyor."})
        tasks = [session.get(context.target_url, timeout=5) for _ in range(30)]
        responses = await asyncio.gather(*tasks, return_exceptions=True)
        for i, res in enumerate(responses):
            if isinstance(res, aiohttp.ClientResponse) and res.status in [429, 503]:
                context.rate_limit_results = {"detected": True, "limit_after_requests": i + 1}
                context.ai_reasoning_log.append({"phase": "rate_limit_finding", "thought": f"✅ Rate limiting {i+1}. istekten sonra tespit edildi."})
                return
        context.rate_limit_results = {"detected": False}

    def _build_final_json(self, context: FirewallContext, error: Exception = None) -> Dict[str, Any]:
        if error:
            error_message = f"{type(error).__name__}: {str(error)}"
            self._add_reasoning(context.ai_reasoning_log, "critical_error", error_message)
            return self._create_final_output(
                success=False,
                ai_summary="Güvenlik analizi kritik bir hatayla karşılaştı.",
                ai_reasoning=context.ai_reasoning_log,
                error=error_message
            )

        # AI Summary oluştur
        summary_parts = []
        if context.detected_wafs: summary_parts.append(f"{len(context.detected_wafs)} WAF ({', '.join([w['name'] for w in context.detected_wafs])}) tespit edildi.")
        else: summary_parts.append("Herhangi bir WAF tespit edilemedi.")
        if context.rate_limit_results.get("detected"): summary_parts.append("Rate limiting aktif.")
        summary = " ".join(summary_parts)

        # Stratejik Öneriler oluştur
        recommendations = []
        if context.detected_wafs:
            for waf in context.detected_wafs:
                for rec in waf['details'].get("specific_recommendations", []):
                    recommendations.append(
                        self._create_recommendation(
                            priority=PriorityLevel.CRITICAL if rec["priority"] == "critical" else 
                                   PriorityLevel.HIGH if rec["priority"] == "high" else
                                   PriorityLevel.MEDIUM if rec["priority"] == "medium" else PriorityLevel.LOW,
                            tool_name=rec["tool"],
                            reason=rec["reason"],
                            params=rec.get("params", {})
                        )
                    )
        else:
            recommendations.append(
                self._create_recommendation(
                    priority=PriorityLevel.CRITICAL,
                    tool_name="vuln_sqli_detector",
                    reason="Hiçbir WAF/CDN koruması tespit edilemedi. Agresif ve doğrudan SQL Injection taraması önceliklidir."
                )
            )
            recommendations.append(
                self._create_recommendation(
                    priority=PriorityLevel.CRITICAL,
                    tool_name="vuln_xss_detector",
                    reason="WAF koruması olmadığından, Cross-Site Scripting zafiyetlerini sömürmek daha kolay olabilir."
                )
            )
        
        if not context.rate_limit_results.get("detected"):
            recommendations.append(
                self._create_recommendation(
                    priority=PriorityLevel.HIGH,
                    tool_name="enum_directory_bruteforcer",
                    reason="Rate limiting tespit edilemedi. Dizin ve parola denemeleri daha yüksek thread sayısı ile yapılabilir.",
                    params={"threads": 100}
                )
            )
        
        if "Content-Security-Policy" not in context.security_headers:
             recommendations.append(
                self._create_recommendation(
                    priority=PriorityLevel.HIGH,
                    tool_name="vuln_xss_detector",
                    reason="Content-Security-Policy (CSP) başlığı eksik. Bu durum, başarılı bir XSS saldırısının etkisini artırır."
                )
            )

        self._add_reasoning(context.ai_reasoning_log, "complete", f"Analiz tamamlandı. {len(recommendations)} adet stratejik öneri oluşturuldu.")
        
        return self._create_final_output(
            success=True,
            data={
                "target": context.target_url,
                "detected_wafs": context.detected_wafs,
                "detected_cdns": context.detected_cdns,
                "security_headers": context.security_headers,
                "rate_limiting": context.rate_limit_results
            },
            ai_summary=summary,
            ai_reasoning=context.ai_reasoning_log,
            recommendations=recommendations
        )

    async def run_tool(self, params: Dict[str, Any]) -> Dict[str, Any]:
        url = params.get("url")
        if not url: 
            return self._create_final_output(
                success=False,
                ai_summary="URL parametresi zorunludur.",
                error="URL parametresi zorunludur."
            )
        if not url.startswith(('http://', 'https://')): 
            url = 'https://' + url

        context = FirewallContext(target_url=url)
        self._add_reasoning(context.ai_reasoning_log, "initialization", f"Hedef {url} için bütünsel güvenlik duruşu analizi başlatılıyor.")

        try:
            async with aiohttp.ClientSession(headers={"User-Agent": "Pentagent/1.0"}) as session:
                await self._passive_scan(session, context)
                await self._active_probe(session, context)
                await self._rate_limit_test(session, context)
            return self._build_final_json(context)
        except aiohttp.ClientConnectorError as e:
            return self._create_final_output(
                success=False,
                ai_summary=f"Bağlantı hatası: Hedef URL '{url}' ulaşılamaz.",
                ai_reasoning=context.ai_reasoning_log,
                error=f"Bağlantı hatası: Hedef URL '{url}' ulaşılamaz. Hata: {e}"
            )
        except Exception as e:
            logger.error(f"Execute metodunda kritik hata: {repr(e)}", exc_info=True)
            return self._create_final_output(
                success=False,
                ai_summary="Güvenlik analizi sırasında kritik bir hata oluştu.",
                ai_reasoning=context.ai_reasoning_log,
                error=str(e)
            )

async def main():
    parser = argparse.ArgumentParser(description="Pentagent Güvenlik Duruşu Analiz Aracı (v2).")
    parser.add_argument("url", help="Analiz edilecek hedef URL (örn: https://example.com)")
    parser.add_argument("--json", action="store_true", help="Çıktıyı ham JSON formatında göster.")
    parser.add_argument("-v", "--verbose", action="store_true", help="Detaylı (INFO seviyesi) logları göster.")
    args = parser.parse_args()

    log_level = logging.INFO if args.verbose else logging.WARNING
    logging.basicConfig(level=log_level, format='%(asctime)s - %(levelname)s - %(message)s', stream=sys.stderr)

    detector = EnumFirewallDetectorTool()
    result = await detector.run_tool({"url": args.url})

    if args.json:
        print(json.dumps(result, indent=2, ensure_ascii=False))
        return

    # Uzman gözüyle, okunabilir ve profesyonel rapor çıktısı
    print("\n" + "="*60 + "\n Pentagent Güvenlik Duruşu Raporu\n" + "="*60)
    if not result.get("success"):
        print(f"HATA: Analiz Basarisiz!\n   Sebep: {result.get('error')}")
    else:
        data = result.get("data", {})
        print(f"Hedef: {data.get('target')}\n")

        # WAF/CDN Analizi
        if data.get('detected_wafs'):
            waf = data['detected_wafs'][0]
            print(f"WAF Tespiti: [Evet] - {waf['name']} ({', '.join(waf['indicators'])})")
            print(f"   Bypass Zorluğu (Tahmini): {waf['details']['bypass_difficulty'].capitalize()}")
        else:
            print("WAF Tespiti: [Hayir] - DIKKAT: Hedef korumasiz olabilir.")
        
        if data.get('detected_cdns'):
            cdn = data['detected_cdns'][0]
            print(f"CDN Tespiti: [Evet] - {cdn['name']} ({', '.join(cdn.get('features', ['Unknown']))})")
        
        # Yapılandırma Analizi
        print("\n" + "-"*25 + " YAPILANDIRMA ANALİZİ " + "-"*25)
        rl = data.get('rate_limiting', {})
        print(f"Rate Limiting: {'Evet' if rl.get('detected') else 'Hayir'}")
        if rl.get('detected'):
            print(f"   Tahmini Limit: ~{rl['limit_after_requests']} seri istek sonrası")
        
        headers = data.get('security_headers', {})
        print(f"Güvenlik Başlıkları: {len(headers)} adet bulundu.")
        if "Content-Security-Policy" not in headers:
            print("  Önemli Eksiklik: Content-Security-Policy (CSP) başlığı bulunamadı.")
        
        # Stratejik Plan
        recommendations = result.get("recommendations", [])
        if recommendations:
            print("\n" + "-"*26 + " STRATEJİK SALDIRI PLANI " + "-"*25)
            for rec in recommendations:
                print(f"  [{rec['priority'].upper()}] -> Çalıştır: {rec['tool']}")
                print(f"    Neden: {rec['reason']}")
    
    # AI Düşünce Akışı (Debug/Verbose için faydalı)
    if args.verbose:
        print("\nAI Düşünce Akışı:")
        for thought in result.get("ai_reasoning", []):
            print(f"   [{thought['phase']}] {thought['thought']}")

    print("="*60)


if __name__ == "__main__":
    asyncio.run(main())